### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_InsightsAnalyticsCSConfiguration
name: "Insights and Analytics configuration for Customer Service (Preview)"
type: solution
metadata: 
  title: "Dataverse Insights and Analytics configuration for Customer Service (Preview) Solution Reference | MicrosoftDocs"
  ms.date: "02/03/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 50798b9d-dfad-4752-84ef-dfdba02d4931
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse Insights and Analytics configuration for Customer Service (Preview) Solution."
namespace: Microsoft.Dynamics.CRM
header:
 description: "Enable Insights and Analytics capability for Customer Service"
 unique_name: msdyn_InsightsAnalyticsCSConfiguration
 version: "1.0.20268.22"
 customization_prefix: msdyn
entities:
  description: "The following entities are included in this solution."
  entity_items:
   - type: Microsoft.Dynamics.CRM.msdyn_datainsightsandanalyticsfeature
     description: "Analytics and insights feature entity"
# This solution includes no actions.
# There are no remarks for this solution.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex