### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_GetDocumentManagementSettingsResponse
name: "msdyn_GetDocumentManagementSettingsResponse"
type: complextype
metadata: 
  title: "Dataverse msdyn_GetDocumentManagementSettingsResponse ComplexType Reference | MicrosoftDocs"
  ms.date: "02/03/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: aae14806-7887-4f0a-8af6-a2493de03cce
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse Web API msdyn_GetDocumentManagementSettingsResponse ComplexType."
namespace: Microsoft.Dynamics.CRM
# This complex type doesn't inherit from another complextype.
description: "For internal use only." 
properties:
  description: "The properties of a complex type contain the structured data of the type."
  property_items:
  - name: DocumentStoreTypes
    type: Edm.String
    nullable: true
    unicode: false
    description: "For internal use only."
    iscollection: false
  - name: BaseURL
    type: Edm.String
    nullable: true
    unicode: false
    description: "For internal use only."
    iscollection: false
# This complex type doesn't have any navigation properties.
usedby:
  description: "The following use the msdyn_GetDocumentManagementSettingsResponse ComplexType."
  usedby_items:
  - name: Microsoft.Dynamics.CRM.msdyn_GetDocumentManagementSettings
    used_as: ReturnType
# There are no remarks for this complex type.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex
