### YamlMime:OData
uid: Microsoft.Dynamics.CRM.apisettings
name: "apisettings"
type: entitytype
metadata: 
  title: "Dataverse EntityType Reference | MicrosoftDocs"
  ms.date: "02/03/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 5e876b04-f046-416e-8f76-4027e3e83408
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse apisettings entitytype."
description: "This entity contains the mapping of entity to the mode with which bulk apis are executed"
header:
  entity_set_path: "[organization URI]/api/data/v9.0/apisettingscollection"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: ApiSettings
  primary_key: apisettingsid
  primary_name_attribute: parententitylogicalname
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: apisettingsid
      type: Edm.Guid
      display_name: "ApiSettings"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: bulkapiexecutionmode
      type: Edm.Int32
      display_name: "Bulk Api Execution Mode for Bulk Apis."
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Disabled"
        - value: 1
          label: "EnableAllPlugins"
        - value: 2
          label: "DisableCustomPlugins"
    - name: componentidunique
      type: Edm.Guid
      display_name: "Row id unique"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: componentstate
      type: Edm.Int32
      display_name: "Component State"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
      options:
        - value: 0
          label: "Published"
        - value: 1
          label: "Unpublished"
        - value: 2
          label: "Deleted"
        - value: 3
          label: "Deleted Unpublished"
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: iscustomizable
      type: Microsoft.Dynamics.CRM.BooleanManagedProperty
      display_name: "Is Customizable"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: ismanaged
      type: Edm.Boolean
      display_name: "Is Managed"
      description: "Indicates whether the solution component is part of a managed solution."
      iscomputed: false
      isreadonly: true
      options:
        - value: 1
          label: "Managed"
        - value: 0
          label: "Unmanaged"
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: overwritetime
      type: Edm.DateTimeOffset
      display_name: "Record Overwrite Time"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: parententitylogicalname
      type: Edm.String
      display_name: "Entity Logical Name For ApiSettings"
      description: "Entity Logical Name For ApiSettings"
      iscomputed: false
      isreadonly: false
    - name: solutionid
      type: Edm.Guid
      display_name: "Solution"
      description: "Unique identifier of the associated solution."
      iscomputed: false
      isreadonly: true
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the ApiSettings"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the ApiSettings"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _organizationid_value
    single_valued_navigation_property:
    - organizationid
    description: "Unique identifier for the organization"
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_apisettings_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_apisettings_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_apisettings_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_apisettings_modifiedonbehalfby
  - name: organizationid
    type: Microsoft.Dynamics.CRM.organization
    partner: organization_apisettings
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: apisettings_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_apisettings
  - name: apisettings_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_apisettings
  - name: apisettings_DuplicateBaseRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: baserecordid_apisettings
  - name: apisettings_DuplicateMatchingRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: duplicaterecordid_apisettings
  - name: apisettings_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_apisettings
  - name: apisettings_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_apisettings
  - name: apisettings_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_apisettings
  - name: apisettings_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_apisettings
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the apisettings entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the apisettings entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.ApiSettings
    description: ""
# There are no remarks for this entity.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex