### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_geolocationsettings
name: "msdyn_geolocationsettings"
type: entitytype
metadata: 
  title: "Microsoft Dataverse EntityType Reference | MicrosoftDocs"
  ms.date: "04/12/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 60f08dd2-7840-471c-b2be-8a73108604d9
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Microsoft Dataverse msdyn_geolocationsettings entitytype."
# This entity doesn't have a description
header:
  entity_set_path: "[organization URI]/api/data/v9.0/msdyn_geolocationsettingscollection"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Geolocation Settings
  primary_key: msdyn_geolocationsettingsid
  primary_name_attribute: msdyn_name
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: msdyn_beaconconfiguration
      type: Edm.String
      display_name: "Beacon Configuration"
      description: "The Beacon configuration"
      iscomputed: false
      isreadonly: false
    - name: msdyn_enablelocationtracking
      type: Edm.Boolean
      display_name: "Enable Location Tracking"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_fridayendtime
      type: Edm.DateTimeOffset
      display_name: "Friday End Time"
      description: "The Friday tracking end time"
      iscomputed: false
      isreadonly: false
    - name: msdyn_fridaystarttime
      type: Edm.DateTimeOffset
      display_name: "Friday Start Time"
      description: "The Friday tracking start time"
      iscomputed: false
      isreadonly: false
    - name: msdyn_geolocationsettingsid
      type: Edm.Guid
      display_name: "GeolocationSettings"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: msdyn_mondayendtime
      type: Edm.DateTimeOffset
      display_name: "Monday End Time"
      description: "The Monday tracking end time"
      iscomputed: false
      isreadonly: false
    - name: msdyn_mondaystarttime
      type: Edm.DateTimeOffset
      display_name: "Monday Start Time"
      description: "The Monday tracking start time"
      iscomputed: false
      isreadonly: false
    - name: msdyn_name
      type: Edm.String
      display_name: "Name"
      description: "The name of the geolocation settings"
      iscomputed: false
      isreadonly: false
    - name: msdyn_refreshintervalseconds
      type: Edm.Int32
      display_name: "Refresh interval"
      description: "The frequency in seconds at which location data should be uploaded from mobile clients to the server"
      iscomputed: false
      isreadonly: false
    - name: msdyn_saturdayendtime
      type: Edm.DateTimeOffset
      display_name: "Saturday End Time"
      description: "The Saturday tracking end time"
      iscomputed: false
      isreadonly: false
    - name: msdyn_saturdaystarttime
      type: Edm.DateTimeOffset
      display_name: "Saturday Start Time"
      description: "The Saturday tracking start time"
      iscomputed: false
      isreadonly: false
    - name: msdyn_sundayendtime
      type: Edm.DateTimeOffset
      display_name: "Sunday End Time"
      description: "The Sunday tracking end time"
      iscomputed: false
      isreadonly: false
    - name: msdyn_sundaystarttime
      type: Edm.DateTimeOffset
      display_name: "Sunday Start Time"
      description: "The Sunday tracking start time"
      iscomputed: false
      isreadonly: false
    - name: msdyn_thursdayendtime
      type: Edm.DateTimeOffset
      display_name: "Thursday End Time"
      description: "The Thursday tracking end time"
      iscomputed: false
      isreadonly: false
    - name: msdyn_thursdaystarttime
      type: Edm.DateTimeOffset
      display_name: "Thursday Start Time"
      description: "The Thursday tracking start time"
      iscomputed: false
      isreadonly: false
    - name: msdyn_tuesdayendtime
      type: Edm.DateTimeOffset
      display_name: "Tuesday End Time"
      description: "The Tuesday tracking end time"
      iscomputed: false
      isreadonly: false
    - name: msdyn_tuesdaystarttime
      type: Edm.DateTimeOffset
      display_name: "Tuesday Start Time"
      description: "The Tuesday tracking start time"
      iscomputed: false
      isreadonly: false
    - name: msdyn_wednesdayendtime
      type: Edm.DateTimeOffset
      display_name: "Wednesday End Time"
      description: "The Wednesday tracking end time"
      iscomputed: false
      isreadonly: false
    - name: msdyn_wednesdaystarttime
      type: Edm.DateTimeOffset
      display_name: "Wednesday Start Time"
      description: "The Wednesday tracking start time"
      iscomputed: false
      isreadonly: false
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the GeolocationSettings"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the GeolocationSettings"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _organizationid_value
    single_valued_navigation_property:
    - organizationid
    description: "Unique identifier for the organization"
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_geolocationsettings_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_geolocationsettings_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_geolocationsettings_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_geolocationsettings_modifiedonbehalfby
  - name: organizationid
    type: Microsoft.Dynamics.CRM.organization
    partner: organization_msdyn_geolocationsettings
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: msdyn_geolocationsettings_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_msdyn_geolocationsettings
  - name: msdyn_geolocationsettings_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_msdyn_geolocationsettings
  - name: msdyn_geolocationsettings_DuplicateBaseRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: baserecordid_msdyn_geolocationsettings
  - name: msdyn_geolocationsettings_DuplicateMatchingRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: duplicaterecordid_msdyn_geolocationsettings
  - name: msdyn_geolocationsettings_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_msdyn_geolocationsettings
  - name: msdyn_geolocationsettings_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_msdyn_geolocationsettings
  - name: msdyn_geolocationsettings_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_msdyn_geolocationsettings
  - name: msdyn_geolocationsettings_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_msdyn_geolocationsettings
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the msdyn_geolocationsettings entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the msdyn_geolocationsettings entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.msdyn_FieldServiceGeolocation
    description: "The Field Service Geolocation solution enables processing and storing of real time tracking information sent by a mobile background service."
  - type: Microsoft.Dynamics.CRM.msdyn_Geolocation
    description: "The Geolocation solution enables processing and storing of real time tracking information sent by a mobile background service."
# There are no remarks for this entity.
href_see_also:
- text: "Use the Microsoft Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex