### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_smartassistconfig
name: "msdyn_smartassistconfig"
type: entitytype
metadata: 
  title: "Dataverse EntityType Reference | MicrosoftDocs"
  ms.date: "02/03/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 1d7eac0b-cc9b-4993-8a22-14546ccec620
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse msdyn_smartassistconfig entitytype."
description: "Stores Smartassist configurations"
header:
  entity_set_path: "[organization URI]/api/data/v9.0/msdyn_smartassistconfigs"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Smartassist configuration
  primary_key: msdyn_smartassistconfigid
  primary_name_attribute: msdyn_name
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: componentidunique
      type: Edm.Guid
      display_name: "Row id unique"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: componentstate
      type: Edm.Int32
      display_name: "Component State"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
      options:
        - value: 0
          label: "Published"
        - value: 1
          label: "Unpublished"
        - value: 2
          label: "Deleted"
        - value: 3
          label: "Deleted Unpublished"
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: iscustomizable
      type: Microsoft.Dynamics.CRM.BooleanManagedProperty
      display_name: "Is Customizable"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: ismanaged
      type: Edm.Boolean
      display_name: "Is Managed"
      description: "Indicates whether the solution component is part of a managed solution."
      iscomputed: false
      isreadonly: true
      options:
        - value: 1
          label: "Managed"
        - value: 0
          label: "Unmanaged"
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: msdyn_iconurl
      type: Edm.String
      display_name: "Icon Webresource URL"
      description: "Icon for the suggestion group container"
      iscomputed: false
      isreadonly: false
    - name: msdyn_isdefault
      type: Edm.Boolean
      display_name: "IsDefault"
      description: "This field denotes whether config is default."
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_maxsuggestioncount
      type: Edm.Int32
      display_name: "Maximum suggestion count"
      description: "This number denotes the maximum number of suggestions that can be displayed in smart assist control"
      iscomputed: false
      isreadonly: false
    - name: msdyn_name
      type: Edm.String
      display_name: "Name"
      description: "The name of the custom entity."
      iscomputed: false
      isreadonly: false
    - name: msdyn_order
      type: Edm.Int32
      display_name: "Order"
      description: "Order in which the entities are grouped in smart assist."
      iscomputed: false
      isreadonly: false
    - name: msdyn_smartassistconfigid
      type: Edm.Guid
      display_name: "Smartassist configuration"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: msdyn_sourceentityname
      type: Edm.String
      display_name: "Source Entity Name"
      description: "Suggestion source entity logical name."
      iscomputed: false
      isreadonly: false
    - name: msdyn_suggestioncontainertitle
      type: Edm.String
      display_name: "Suggestion panel title"
      description: "This will be used as a title for entity suggestion panel"
      iscomputed: false
      isreadonly: false
    - name: msdyn_suggestioncontrolconfiguniquename
      type: Edm.String
      display_name: "Suggestion Control Config Uniquename"
      description: "Unique name of the suggestion control configuration entity. if suggestion type is adaptive card, then it should refer to the associated adaptive configuration."
      iscomputed: false
      isreadonly: false
    - name: msdyn_suggestioncontroltype
      type: Edm.Int32
      display_name: "Suggestioncontroltype"
      description: "Denotes the control type for suggestions, (e.g) Adaptive card"
      iscomputed: false
      isreadonly: false
      options:
        - value: 192360000
          label: "Adaptive Card"
    - name: msdyn_suggestionprovider
      type: Edm.String
      display_name: "Suggestion Provider"
      description: "Provide the class name of Suggestion provider"
      iscomputed: false
      isreadonly: false
    - name: msdyn_suggestiontype
      type: Edm.Int32
      display_name: "Suggestiontype"
      description: "Denotes the type of suggestions like Similar case or KB article suggestion"
      iscomputed: false
      isreadonly: false
      options:
        - value: 192360000
          label: "Knowledge Article Suggestion"
        - value: 192360001
          label: "Similar Case Suggestion"
        - value: 192360002
          label: "Bot Suggestion"
    - name: msdyn_suggestionwebresourceurl
      type: Edm.String
      display_name: "Suggestion Webresource URL"
      description: "Suggestion Webresource which brings smart assist actions or api to retrieve suggestions"
      iscomputed: false
      isreadonly: false
    - name: msdyn_uniquename
      type: Edm.String
      display_name: "Unique Name"
      description: "Unique Name for the entity."
      iscomputed: false
      isreadonly: false
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: overwritetime
      type: Edm.DateTimeOffset
      display_name: "Record Overwrite Time"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: solutionid
      type: Edm.Guid
      display_name: "Solution"
      description: "Unique identifier of the associated solution."
      iscomputed: false
      isreadonly: true
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the Smartassist configuration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the Smartassist configuration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _organizationid_value
    single_valued_navigation_property:
    - organizationid
    description: "Unique identifier for the organization"
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_smartassistconfig_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_smartassistconfig_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_smartassistconfig_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_smartassistconfig_modifiedonbehalfby
  - name: organizationid
    type: Microsoft.Dynamics.CRM.organization
    partner: organization_msdyn_smartassistconfig
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: msdyn_smartassistconfig_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_msdyn_smartassistconfig
  - name: msdyn_smartassistconfig_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_msdyn_smartassistconfig
  - name: msdyn_smartassistconfig_DuplicateBaseRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: baserecordid_msdyn_smartassistconfig
  - name: msdyn_smartassistconfig_DuplicateMatchingRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: duplicaterecordid_msdyn_smartassistconfig
  - name: msdyn_smartassistconfig_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_msdyn_smartassistconfig
  - name: msdyn_smartassistconfig_msdyn_appconfig
    type: Microsoft.Dynamics.CRM.msdyn_appconfiguration
    partner: msdyn_smartassistconfig_msdyn_appconfig
  - name: msdyn_smartassistconfig_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_msdyn_smartassistconfig
  - name: msdyn_smartassistconfig_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_msdyn_smartassistconfig
  - name: msdyn_smartassistconfig_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_msdyn_smartassistconfig
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the msdyn_smartassistconfig entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the msdyn_smartassistconfig entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.msdyn_smartassist
    description: "This solution enables smart assist functionality for agents. "
# This entity has no remarks.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex