### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_smartassistconfig_msdyn_appconfig
name: "msdyn_smartassistconfig_msdyn_appconfig"
type: entitytype
metadata: 
  title: "Dataverse EntityType Reference | MicrosoftDocs"
  ms.date: "02/03/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 1767ffea-db1a-435b-afbc-efb1c1110764
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse msdyn_smartassistconfig_msdyn_appconfig entitytype."
# This entity doesn't have a description
header:
  entity_set_path: "[organization URI]/api/data/v9.0/msdyn_smartassistconfig_msdyn_appconfigset"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  # This entity doesn't have a display name
  primary_key: msdyn_smartassistconfig_msdyn_appconfigid
  # This entity doesn't have a primaryAttributeName
  operations_supported:
  - GET (RetrieveMultiple Only)
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: componentidunique
      type: Edm.Guid
      display_name: "Row id unique"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: componentstate
      type: Edm.Int32
      display_name: "Component State"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
      options:
        - value: 0
          label: "Published"
        - value: 1
          label: "Unpublished"
        - value: 2
          label: "Deleted"
        - value: 3
          label: "Deleted Unpublished"
    - name: iscustomizable
      type: Microsoft.Dynamics.CRM.BooleanManagedProperty
      display_name: "Is Customizable"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: ismanaged
      type: Edm.Boolean
      display_name: "Is Managed"
      description: "Indicates whether the solution component is part of a managed solution."
      iscomputed: false
      isreadonly: true
      options:
        - value: 1
          label: "Managed"
        - value: 0
          label: "Unmanaged"
    - name: msdyn_appconfigurationid
      type: Edm.Guid
      display_name: ""
      description: ""
      iscomputed: false
      isreadonly: true
    - name: msdyn_smartassistconfig_msdyn_appconfigid
      type: Edm.Guid
      display_name: ""
      description: ""
      iscomputed: false
      isreadonly: true
    - name: msdyn_smartassistconfigid
      type: Edm.Guid
      display_name: ""
      description: ""
      iscomputed: false
      isreadonly: true
    - name: overwritetime
      type: Edm.DateTimeOffset
      display_name: "Record Overwrite Time"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: solutionid
      type: Edm.Guid
      display_name: "Solution"
      description: "Unique identifier of the associated solution."
      iscomputed: false
      isreadonly: true
    - name: versionnumber
      type: Edm.Int64
      display_name: ""
      description: ""
      iscomputed: false
      isreadonly: true
# This entity has no lookup properties
# This entity has no single-valued navigation properties
# This entity has no collection-valued navigation properties
# This entity has no derived entities.
# This entity has no operations
# This entity is not included in any solutions.
# This entity has no remarks.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex