### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_playbookactivityattribute
name: "msdyn_playbookactivityattribute"
type: entitytype
metadata: 
  title: "Dataverse EntityType Reference | MicrosoftDocs"
  ms.date: "02/03/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 60953a8f-e4e6-4b3a-8f4a-1e9786838b63
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse msdyn_playbookactivityattribute entitytype."
description: "Stores attribute names and values of the playbook activity."
header:
  entity_set_path: "[organization URI]/api/data/v9.0/msdyn_playbookactivityattributes"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Playbook activity attribute
  primary_key: msdyn_playbookactivityattributeid
  primary_name_attribute: msdyn_attributeLogicalName
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: msdyn_attributeLogicalName
      type: Edm.String
      display_name: "Attribute Name"
      description: "Type the name of the playbook activity attribute."
      iscomputed: false
      isreadonly: false
    - name: msdyn_attributeType
      type: Edm.Int32
      display_name: "Attribute type"
      description: "Stores the data type of the attribute."
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "string"
        - value: 2
          label: "integer"
        - value: 3
          label: "datetime"
        - value: 4
          label: "boolean"
        - value: 5
          label: "optionset"
    - name: msdyn_attributeValue
      type: Edm.String
      display_name: "Attribute value"
      description: "Stores the value of the attribute."
      iscomputed: false
      isreadonly: false
    - name: msdyn_playbookactivityattributeid
      type: Edm.Guid
      display_name: "Playbook activity attribute"
      description: "Shows the ID of the playbook activity attribute."
      iscomputed: false
      isreadonly: false
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the PlaybookActivityAttribute"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Draft"
        - value: 1
          label: "Published"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the PlaybookActivityAttribute"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Draft"
        - value: 2
          label: "Published"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _msdyn_playbookactivityid_value
    single_valued_navigation_property:
    - msdyn_playbookactivityid
    description: "Shows the ID of the playbook activity associated with the playbook activity attribute."
  - name: _ownerid_value
    single_valued_navigation_property:
    - ownerid
    description: "Owner Id"
  - name: _owningbusinessunit_value
    single_valued_navigation_property:
    - owningbusinessunit
    description: "Unique identifier for the business unit that owns the record"
  - name: _owningteam_value
    single_valued_navigation_property:
    - owningteam
    description: "Unique identifier for the team that owns the record."
  - name: _owninguser_value
    single_valued_navigation_property:
    - owninguser
    description: "Unique identifier for the user that owns the record."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_playbookactivityattribute_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_playbookactivityattribute_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_playbookactivityattribute_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_playbookactivityattribute_modifiedonbehalfby
  - name: msdyn_playbookactivityid
    type: Microsoft.Dynamics.CRM.msdyn_playbookactivity
    partner: msdyn_playbookactivity_msdyn_playbookactivityattribute
  - name: ownerid
    type: Microsoft.Dynamics.CRM.principal
    partner: owner_msdyn_playbookactivityattribute
  - name: owningbusinessunit
    type: Microsoft.Dynamics.CRM.businessunit
    partner: business_unit_msdyn_playbookactivityattribute
  - name: owningteam
    type: Microsoft.Dynamics.CRM.team
    partner: team_msdyn_playbookactivityattribute
  - name: owninguser
    type: Microsoft.Dynamics.CRM.systemuser
    partner: user_msdyn_playbookactivityattribute
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: msdyn_playbookactivityattribute_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_msdyn_playbookactivityattribute
  - name: msdyn_playbookactivityattribute_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_msdyn_playbookactivityattribute
  - name: msdyn_playbookactivityattribute_DuplicateBaseRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: baserecordid_msdyn_playbookactivityattribute
  - name: msdyn_playbookactivityattribute_DuplicateMatchingRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: duplicaterecordid_msdyn_playbookactivityattribute
  - name: msdyn_playbookactivityattribute_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_msdyn_playbookactivityattribute
  - name: msdyn_playbookactivityattribute_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_msdyn_playbookactivityattribute
  - name: msdyn_playbookactivityattribute_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_msdyn_playbookactivityattribute
  - name: msdyn_playbookactivityattribute_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_msdyn_playbookactivityattribute
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the msdyn_playbookactivityattribute entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.GrantAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.ModifyAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrievePrincipalAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrieveSharedPrincipalsAndAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RevokeAccess
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the msdyn_playbookactivityattribute entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.msdyn_Playbook
    description: "Playbook"
# There are no remarks for this entity.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex