### YamlMime:OData
uid: Microsoft.Dynamics.CRM.package
name: "package"
type: entitytype
metadata: 
  title: "Microsoft Dataverse EntityType Reference | MicrosoftDocs"
  ms.date: "04/12/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 53f687ad-3505-410e-93d5-68eae30d63df
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Microsoft Dataverse package entitytype."
# This entity doesn't have a description
header:
  entity_set_path: "[organization URI]/api/data/v9.0/packages"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Package
  primary_key: packageid
  primary_name_attribute: packageuniquename
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: appid
      type: Edm.Guid
      display_name: "AppId"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: applicationname
      type: Edm.String
      display_name: "ApplicationName"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: installedon
      type: Edm.DateTimeOffset
      display_name: "Installed On"
      description: "Date and time when the package was first installed."
      iscomputed: false
      isreadonly: false
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: packageid
      type: Edm.Guid
      display_name: "PackageId"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: packageinstanceid
      type: Edm.Guid
      display_name: "PackageInstanceId"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: packageinstanceoperationid
      type: Edm.Guid
      display_name: "PackageInstanceOperationId"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: packageuniquename
      type: Edm.String
      display_name: "Package Unique Name"
      description: "The unique name of the package."
      iscomputed: false
      isreadonly: false
    - name: packageversion
      type: Edm.String
      display_name: "PackageVersion"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: publisherid
      type: Edm.Guid
      display_name: "PublisherId"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: publishername
      type: Edm.String
      display_name: "PublisherName"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the Package"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the Package"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: tpspackageid
      type: Edm.Guid
      display_name: "TPSPackageId"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _organizationid_value
    single_valued_navigation_property:
    - organizationid
    description: "Unique identifier for the organization"
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_package_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_package_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_package_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_package_modifiedonbehalfby
  - name: organizationid
    type: Microsoft.Dynamics.CRM.organization
    partner: organization_package
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: package_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_package
  - name: package_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_package
  - name: package_DuplicateBaseRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: baserecordid_package
  - name: package_DuplicateMatchingRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: duplicaterecordid_package
  - name: package_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_package
  - name: package_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_package
  - name: package_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_package
  - name: package_solution
    type: Microsoft.Dynamics.CRM.solution
    partner: package_solution
  - name: package_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_package
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the package entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the package entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.msdyn_SolutionPackageMapping
    description: ""
# There are no remarks for this entity.
href_see_also:
- text: "Use the Microsoft Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex