### YamlMime:OData
uid: Microsoft.Dynamics.CRM.solutioncomponentconfiguration
name: "solutioncomponentconfiguration"
type: entitytype
metadata: 
  title: "Dataverse EntityType Reference | MicrosoftDocs"
  ms.date: "02/03/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: f1f3a2d7-0ba1-41a3-ab7f-87ba5b964542
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse solutioncomponentconfiguration entitytype."
# This entity doesn't have a description
header:
  entity_set_path: "[organization URI]/api/data/v9.0/solutioncomponentconfigurations"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Solution Component Configuration
  primary_key: solutioncomponentconfigurationid
  primary_name_attribute: name
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: componentidunique
      type: Edm.Guid
      display_name: "Row id unique"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: componentstate
      type: Edm.Int32
      display_name: "Component State"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
      options:
        - value: 0
          label: "Published"
        - value: 1
          label: "Unpublished"
        - value: 2
          label: "Deleted"
        - value: 3
          label: "Deleted Unpublished"
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: fileformat
      type: Edm.Int32
      display_name: "File Format"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "xml"
        - value: 1
          label: "json"
    - name: filescope
      type: Edm.Int32
      display_name: "File Scope"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 100000000
          label: "None"
        - value: 0
          label: "None"
        - value: 1
          label: "Individual"
        - value: 2
          label: "Global"
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: iscustomizable
      type: Microsoft.Dynamics.CRM.BooleanManagedProperty
      display_name: "Is Customizable"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: isdisplayable
      type: Edm.Boolean
      display_name: "Displayable"
      description: "Boolean that indicates if the component has user interface enabled."
      iscomputed: false
      isreadonly: false
    - name: ismanaged
      type: Edm.Boolean
      display_name: "Is Managed"
      description: "Indicates whether the solution component is part of a managed solution."
      iscomputed: false
      isreadonly: true
      options:
        - value: 1
          label: "Managed"
        - value: 0
          label: "Unmanaged"
    - name: issoftdeleteenabled
      type: Edm.Boolean
      display_name: "IsSoftDeleteEnabled"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: name
      type: Edm.String
      display_name: "Name"
      description: "The name of the custom entity."
      iscomputed: false
      isreadonly: false
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: overwritetime
      type: Edm.DateTimeOffset
      display_name: "Record Overwrite Time"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: solutioncomponentconfigurationid
      type: Edm.Guid
      display_name: "Solution Component Configuration"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: solutionid
      type: Edm.Guid
      display_name: "Solution"
      description: "Unique identifier of the associated solution."
      iscomputed: false
      isreadonly: true
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the Solution Component Configuration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the Solution Component Configuration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _entityid_value
    single_valued_navigation_property:
    - EntityId
    description: "Unique identifier for Entity associated with Solution Component Configuration."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _organizationid_value
    single_valued_navigation_property:
    - organizationid
    description: "Unique identifier for the organization"
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_solutioncomponentconfiguration_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_solutioncomponentconfiguration_createdonbehalfby
  - name: EntityId
    type: Microsoft.Dynamics.CRM.entity
    partner: entity_solutioncomponentconfiguration
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_solutioncomponentconfiguration_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_solutioncomponentconfiguration_modifiedonbehalfby
  - name: organizationid
    type: Microsoft.Dynamics.CRM.organization
    partner: organization_solutioncomponentconfiguration
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: solutioncomponentconfig_solutioncomponentattrconfig
    type: Microsoft.Dynamics.CRM.solutioncomponentattributeconfiguration
    partner: solutioncomponentconfigurationid
  - name: solutioncomponentconfiguration_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_solutioncomponentconfiguration
  - name: solutioncomponentconfiguration_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_solutioncomponentconfiguration
  - name: solutioncomponentconfiguration_DuplicateBaseRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: baserecordid_solutioncomponentconfiguration
  - name: solutioncomponentconfiguration_DuplicateMatchingRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: duplicaterecordid_solutioncomponentconfiguration
  - name: solutioncomponentconfiguration_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_solutioncomponentconfiguration
  - name: solutioncomponentconfiguration_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_solutioncomponentconfiguration
  - name: solutioncomponentconfiguration_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_solutioncomponentconfiguration
  - name: solutioncomponentconfiguration_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_solutioncomponentconfiguration
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the solutioncomponentconfiguration entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the solutioncomponentconfiguration entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.datalakeworkspaces
    description: ""
  - type: Microsoft.Dynamics.CRM.PowerVirtualAgents
    description: "For internal use, by the Power Virtual Agents services only."
  - type: Microsoft.Dynamics.CRM.SolutionComponentConfiguration
    description: ""
# There are no remarks for this entity.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex