### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_RetrieveTypeValuesFromDCI
name: "msdyn_RetrieveTypeValuesFromDCI"
type: action
metadata: 
  title: "Dataverse Action Reference | MicrosoftDocs"
  ms.date: "02/03/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 02ec7129-8be2-4ad7-9dfa-77ddad799fb5
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse msdyn_RetrieveTypeValuesFromDCI Action."
namespace: Microsoft.Dynamics.CRM
# This Action has no description.
owningsolution: Microsoft.Dynamics.CRM.SICommon
# This action has no bound entities.
isbound: false
parameters:
  description: "Parameters allow for data to be passed to the action."
  parameter_items:
  - name: CrmRecord
    type: Microsoft.Dynamics.CRM.crmbaseentity
    nullable: false
    unicode: true
    description: ""
  - name: ResourceType
    type: Edm.Int32
    nullable: false
    unicode: true
    description: ""
  - name: ResourceTypeName
    type: Edm.String
    nullable: false
    unicode: false
    description: ""
  - name: StartDate
    type: Edm.DateTimeOffset
    nullable: true
    unicode: true
    description: ""
  - name: EndDate
    type: Edm.DateTimeOffset
    nullable: true
    unicode: true
    description: ""
return_type:
  description: "The msdyn_RetrieveTypeValuesFromDCI action returns the following value."
  iscollection: false
  nullable: false
  type: Microsoft.Dynamics.CRM.msdyn_RetrieveTypeValuesFromDCIResponse
# This action has no identified unbound entities.
# There are no remarks for this action.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex