### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_GetDocumentManagementSettings
name: "msdyn_GetDocumentManagementSettings"
type: action
metadata: 
  title: "Dataverse Action Reference | MicrosoftDocs"
  ms.date: "02/03/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 6b181829-df48-47b8-8e61-0bfce3516792
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse msdyn_GetDocumentManagementSettings Action."
namespace: Microsoft.Dynamics.CRM
description: "For internal use only."
owningsolution: Microsoft.Dynamics.CRM.ProjectService
# This action has no bound entities.
isbound: false
# This action has no parameters.
hasparameters: false
return_type:
  description: "The msdyn_GetDocumentManagementSettings action returns the following value."
  iscollection: false
  nullable: false
  type: Microsoft.Dynamics.CRM.msdyn_GetDocumentManagementSettingsResponse
# This action has no identified unbound entities.
# There are no remarks for this action.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex