### YamlMime:OData
uid: Microsoft.Dynamics.CRM.UpsertEnvironmentVariable
name: "UpsertEnvironmentVariable"
type: action
metadata: 
  title: "Dataverse Action Reference | MicrosoftDocs"
  ms.date: "02/03/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 95509a79-cdc3-4c6f-8c56-c5da75bd08c9
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse UpsertEnvironmentVariable Action."
namespace: Microsoft.Dynamics.CRM
# This Action has no description.
owningsolution: Microsoft.Dynamics.CRM.System
# This action has no bound entities.
isbound: false
parameters:
  description: "Parameters allow for data to be passed to the action."
  parameter_items:
  - name: DisplayName
    type: Edm.String
    nullable: true
    unicode: false
    description: ""
  - name: SchemaName
    type: Edm.String
    nullable: false
    unicode: false
    description: ""
  - name: Type
    type: Edm.Int32
    nullable: false
    unicode: true
    description: ""
  - name: DefaultValue
    type: Edm.String
    nullable: true
    unicode: false
    description: ""
  - name: ConnectionId
    type: Edm.String
    nullable: true
    unicode: false
    description: ""
  - name: Value
    type: Edm.String
    nullable: true
    unicode: false
    description: ""
  - name: ParameterKey
    type: Edm.String
    nullable: true
    unicode: false
    description: ""
  - name: ApiId
    type: Edm.String
    nullable: true
    unicode: false
    description: ""
# This action has no return value.
hasreturnvalue: false
# This action has no identified unbound entities.
# This action has no remarks.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex