### YamlMime:OData
uid: Microsoft.Dynamics.CRM.RetrieveEnvironmentVariableValue
name: "RetrieveEnvironmentVariableValue"
type: function
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement RetrieveEnvironmentVariableValue Function Reference | MicrosoftDocs"
  ms.date: "02/03/2021"
  ms.service: "powerapps"
  ms.topic: "reference"
  ms.assetid: 15aebb3f-3dfb-44a4-be89-e4dfd31935b1
  author: "kumarvivek"
  ms.author: "kvivek"
  manager: "annbe"
  meta-description: "Reference information about the Dataverse RetrieveEnvironmentVariableValue Function."
namespace: Microsoft.Dynamics.CRM
description: ""
iscomposable: false
# This function is not bound to any entities.
isbound: false
parameters:
  description: "Parameters allow for data to be passed to the function."
  parameter_items:
  - name: DefinitionSchemaName
    type: Edm.String
    nullable: false
    unicode: false
    description: ""
    iscollection: false
return_type:
  description: "The RetrieveEnvironmentVariableValue function returns the following value."
  type: Microsoft.Dynamics.CRM.RetrieveEnvironmentVariableValueResponse
  iscollection: false
  nullable: false
entities:
  description: "Use the RetrieveEnvironmentVariableValue function with this entity type:"
  entity_items:
  - type: Microsoft.Dynamics.CRM.environmentvariabledefinition
    displayName: "Environment Variable Definition"
    description: "Contains information about the settable variable: its type, default value, and etc."
# This function has no remarks.
href_see_also:
- text: "Use the Dataverse Web API"
  href: "https://docs.microsoft.com/powerapps/developer/data-platform/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex